---
apiVersion: v1
kind: Namespace
metadata:
  name: crankbit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crankbit
  name: crankbit-backend-main-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: crankbit-backend-main
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crankbit-backend-main
    spec:
      containers:
      - image: 349498089405.dkr.ecr.ap-southeast-2.amazonaws.com/crankbit-backend-main:latest
        imagePullPolicy: Always
        name: crankbit-backend-main
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: crankbit
  name: crankbit-backend-main-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: crankbit-backend-main
